### ISSUE TITLE
formas irregulares não adjacentes

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/tools#12]
@arademaker e @analununes, no atual *irregs.txt* temos:

> quises	FUT-SUBJ-2SG-SUFFIX	querer
> quisermos	FUT-SUBJ-1PL-SUFFIX	querer
> quiseres	FUT-SUBJ-2SG-SUFFIX	querer 

Em vez disso, deveríamos ter algo como:

> quises	FUT-SUBJ-2SG-SUFFIX	querer
> quiseres	FUT-SUBJ-2SG-SUFFIX	querer
> quisermos	FUT-SUBJ-1PL-SUFFIX	querer

No MorphoBr:

`~/MorphoBr/verbs $ grep -Ph "\tquerer\+V\+SBJF\+2\+SG" *.dict`

> quiseres	querer+V+SBJF+2+SG
> quises	querer+V+SBJF+2+SG

A segunda forma, ao que tudo indica, é espúria. Mas o fato de que o algoritmo não gera mais de uma forma irregular em sequência parece apontar para o mesmo possível problema de design que levantei anteriormente, por exemplo, em comentário em #10.

**Comment by leoalenc** [comment]
@analununes e @arademaker, testei a colocação das duas variantes uma distante da outra e não causou problema no *parsing* no LKB. No entanto, acho recomendável agrupar, porque fica mais organizado.

**Comment by analununes** [comment]
@leoalenc, no commit d9421691be0860d291d83dbfa550de774a309b45 organizei as saídas ordenando por regra e forma dentro do grupo de um lema. Os casos apontados acima agora estão assim:

```
quiserdes	FUT-SUBJ-2PL-SUFFIX	querer
quiseres	FUT-SUBJ-2SG-SUFFIX	querer
quises	FUT-SUBJ-2SG-SUFFIX	querer
quisem	FUT-SUBJ-3PL-SUFFIX	querer
quiserem	FUT-SUBJ-3PL-SUFFIX	querer
quis	FUT-SUBJ-3SG-SUFFIX	querer
```
Arquivo completo: 
[irregs.txt](https://github.com/LR-POR/tools/files/7324062/irregs.txt)
