### ISSUE TITLE
Correções nos arquivos de clíticos do MorphoBr

### ISSUE THREAD

**Issue by analununes** [LR-POR/tools#29]
O objetivo dessa issue é corrigir os erros das issues [48](https://github.com/LR-POR/MorphoBr/issues/48) e [81](https://github.com/LR-POR/MorphoBr/issues/81) do MorphoBr.

A issue 48 será resolvlda adicionando a tag `V` quando ela não estiver presente na entrada.
Para corrigir a questão da issue 81 a tag `PTPASS` será trocada pela tag `PTPST, que ainda não foi incluída nesse repositório.`

**Comment by analununes** [comment]
Como o diretório de clíticos não está organizado alfabeticamente como os outros diretórios do MorphoBr - e não parece ser uma boa ideia usar essa organização devido ao tamanho dos arquivos que seriam gerados - implementei no commit 09113d1bf904327ed16536da7641b42183263e6b a função `delclitics` em vez de usar a função `delete`, que depende da organização em ordem alfabética.

A função `delclitics`, funciona de forma simples, para cada entrada de cada arquivo, se a entrada existe na lista de entradas a serem apagadas, a mesma é eliminada.

**Comment by arademaker** [comment]
> e não parece ser uma boa ideia usar essa organização devido ao tamanho dos arquivos que seriam gerados 

Não está claro para mim esta parte, pode esclarecer. Em comentário anterior, sugeri uma organização da biblioteca en camadas, o que resultaria em uma única função para adição e outra para remoção de entradas.

**Comment by analununes** [comment]
> > e não parece ser uma boa ideia usar essa organização devido ao tamanho dos arquivos que seriam gerados
> 
> Não está claro para mim esta parte, pode esclarecer. Em comentário anterior, sugeri uma organização da biblioteca en camadas, o que resultaria em uma única função para adição e outra para remoção de entradas.

Estava preocupada com o tamanho dos arquivos que seriam gerados mas agora vejo que realmente faz sentido padronizar os diretórios e utilizar funções únicas. Abri a issue #31 para reorganizar os arquivos de clíticos.
