### ISSUE TITLE
we don't need it

### ISSUE THREAD

**Issue by arademaker** [LR-POR/tools#8]
https://github.com/LR-POR/tools/blob/65140eff2064674d7b4e2393a079e1b6fa14448e/tools/src/MorphoTools.hs#L57

Vide

https://hackage.haskell.org/package/base-4.15.0.0/docs/GHC-List.html#v:elem

**Comment by analununes** [comment]
Resolvido em 18a096c17b6395957d40a5c864d5866c6e3bba43.
